name: Trigger CloudFlare Pages Deploy Hook

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger CloudFlare Pages Deploy Hook
      run: curl -X POST "${{ secrets.CF_PAGES_WEBHOOK_URL }}"
